version: '3.7'

services:
  main:
    container_name: optimhire-challenge-docker
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 3000:3000
    command: npm run start:dev
    environment:
      - MONGODB_CONNECTION_URI=mongodb://mongodb:27017/optimhire_challenge
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017